# Generated by Django 5.2.2 on 2025-06-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('L1', models.FloatField(blank=True, null=True)),
                ('L2', models.FloatField(blank=True, null=True)),
                ('L3', models.FloatField(blank=True, null=True)),
                ('GEN', models.FloatField(blank=True, null=True)),
                ('L1_L2', models.FloatField(blank=True, null=True)),
                ('L2_L3', models.FloatField(blank=True, null=True)),
                ('L3_L1', models.FloatField(blank=True, null=True)),
                ('ampL1', models.FloatField(blank=True, null=True)),
                ('ampL2', models.FloatField(blank=True, null=True)),
                ('ampL3', models.FloatField(blank=True, null=True)),
                ('kW', models.FloatField(blank=True, null=True)),
                ('kVA', models.FloatField(blank=True, null=True)),
                ('kvar', models.FloatField(blank=True, null=True)),
                ('kWh', models.FloatField(blank=True, null=True)),
                ('kVAh', models.FloatField(blank=True, null=True)),
                ('kvarh', models.FloatField(blank=True, null=True)),
                ('oilPressure', models.FloatField(blank=True, null=True)),
                ('coolantTemp', models.FloatField(blank=True, null=True)),
                ('fuelLevel', models.FloatField(blank=True, null=True)),
                ('batteryVoltage', models.FloatField(blank=True, null=True)),
                ('chargeAltVoltage', models.FloatField(blank=True, null=True)),
                ('statusStop', models.BooleanField(default=False)),
                ('statusStart', models.BooleanField(default=False)),
                ('statusAuto', models.BooleanField(default=False)),
                ('statusManual', models.BooleanField(default=False)),
                ('lastShutdownTime', models.DateTimeField(blank=True, null=True)),
                ('electricTrip', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
